<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions">
    <xsl:output method="text" indent="yes"/>
    <xsl:param name="OrderSequence"/>
    <xsl:param name="Account"/>
    <xsl:variable name="Account-x" select="json-to-xml($Account)"/>
    <xsl:variable name="mapped-xml">
        <map xmlns="http://www.w3.org/2005/xpath-functions">
            <string key="OrderId">
                <xsl:value-of select="concat($Account-x/fn:map/fn:string[@key='AccountId'],'-', $OrderSequence)"/>
            </string>
            <string key="OrderPerson">
                <xsl:value-of select="$Account-x/fn:map/fn:string[@key='Name']"/>
            </string>
            <map key="ShipTo">
                <string key="Address">
                    <xsl:value-of select="$Account-x/fn:map/fn:map[@key='Address']/fn:string[@key='Street']"/>
                </string>
                <string key="City">
                    <xsl:value-of select="$Account-x/fn:map/fn:map[@key='Address']/fn:string[@key='City']"/>
                </string>
                <string key="State">
                    <xsl:value-of select="$Account-x/fn:map/fn:map[@key='Address']/fn:string[@key='State']"/>
                </string>
                <string key="Country">
                    <xsl:value-of select="$Account-x/fn:map/fn:map[@key='Address']/fn:string[@key='Country']"/>
                </string>
            </map>
            <array key="Item">
                <xsl:for-each select="Cart/fn:array/fn:map">
                    <map>
                        <string key="Title">
                            <xsl:value-of select="../../Item/Title"/>
                        </string>
                        <number key="Quantity">
                            <xsl:value-of select="../../Item/Quantity"/>
                        </number>
                        <number key="Price">
                            <xsl:value-of select="../../Item/Price"/>
                        </number>
                    </map>
                </xsl:for-each>
            </array>
        </map>
    </xsl:variable>
    <xsl:template match="/">
        <xsl:value-of select="xml-to-json($mapped-xml)"/>
    </xsl:template>
</xsl:stylesheet>