<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions">
    <xsl:output method="text" indent="yes"/>
    <xsl:param name="OrderSequence"/>
    <xsl:param name="Cart"/>
    <xsl:param name="Account"/>
    <xsl:variable name="mapped-xml">
        <map xmlns="http://www.w3.org/2005/xpath-functions">
            <string key="OrderId">
                <xsl:value-of select="$Account/Account/@AccountId"/>
            </string>
            <map key="ShipTo">
                <string key="Name">
                    <xsl:value-of select="$Account/Account/Name"/>
                </string>
                <string key="Address">
                    <xsl:value-of select="$Account/Account/Address"/>
                </string>
                <string key="City">
                    <xsl:value-of select="$Account/Account/City"/>
                </string>
                <string key="State">
                    <xsl:value-of select="$Account/Account/State"/>
                </string>
                <string key="Country">
                    <xsl:value-of select="$Account/Account/Country"/>
                </string>
            </map>
            <array key="Item">
                <xsl:for-each select="$Cart/fn:array/fn:map">
                    <map>
                        <string key="Title">
                            <xsl:value-of select="$Cart/Cart/Item/Title"/>
                        </string>
                        <number key="Quantity">
                            <xsl:value-of select="$Cart/Cart/Item/Quantity"/>
                        </number>
                        <number key="Price">
                            <xsl:value-of select="$Cart/Cart/Item/Price"/>
                        </number>
                    </map>
                </xsl:for-each>
            </array>
        </map>
    </xsl:variable>
    <xsl:template match="/">
        <xsl:value-of select="xml-to-json($mapped-xml)"/>
    </xsl:template>
</xsl:stylesheet>